### PR TITLE
Warn when the Qt application quits 'early'

### PR DESCRIPTION
**Pull request by altendky**
Follows from https://github.com/altendky/qtrio/issues/262.

### CODE REVIEW

**Comment by altendky** [comment]
@vxgmichel, would you like to review or test this before I merge?  Does it fulfill your interest in a notification?

**Review by vxgmichel — APPROVED** [review]
Looks good to me :+1:

I ran a quick test with the problem I originally faced with #262. I was surprised to not see the warning appear before I realized two Qt organizations were created:
- one in `qtrio.run` 
- and another one in the main async function

Weirdly enough, this caused the `aboutToQuit` of the first application to not be emitted. Once I made sure the app was created before runniong `qtrio.run`, the PR worked as expected.

**Comment by altendky** [comment]
That's...  super weird.  The Qt application is a singleton.  You shouldn't be able to have two.

```pycon
>>> from PySide2 import QtCore
>>> a1 = QtCore.QCoreApplication([])
>>> a2 = QtCore.QCoreApplication([])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Please destroy the QCoreApplication singleton before creating a new QCoreApplication instance.
```

But with PyQt5 it does let you do that...  uh...

```pycon
>>> from PyQt5 import QtCore
>>> a1 = QtCore.QCoreApplication([])
>>> a2 = QtCore.QCoreApplication([])
>>> a1
<PyQt5.QtCore.QCoreApplication object at 0x7f3c88b0e550>
>>> a2
<PyQt5.QtCore.QCoreApplication object at 0x7f3c8584d4c0>
```

And PyQt6 (6.1.1) still does.

```pycon
>>> from PyQt6 import QtCore
>>> a1 = QtCore.QCoreApplication([])
>>> a2 = QtCore.QCoreApplication([])
>>> a1
<PyQt6.QtCore.QCoreApplication object at 0x7f73ce8b0550>
>>> a2
<PyQt6.QtCore.QCoreApplication object at 0x7f73ce7e80d0>
```

**Comment by altendky** [comment]
https://doc.qt.io/qt-6/qcoreapplication.html
> For non-GUI application that uses Qt, there should be exactly one QCoreApplication object.

So it apparently isn't a singleton at the C++ level, you are just supposed to not create multiple.  [Someone did some experimentation](https://stackoverflow.com/a/46650157/228539) for us as to what the implications of having multiple applications are.  I recreated the signal separation issue.

```python
from PyQt6 import QtCore

a1 = QtCore.QCoreApplication([])
a2 = QtCore.QCoreApplication([])

def f1():
    print("f1")

def f2():
    print("f2")

a1.applicationNameChanged.connect(f1)
a2.applicationNameChanged.connect(f2)

print("---")
a1.applicationNameChanged.emit()
print("---")
a2.applicationNameChanged.emit()
print("---")
```

```
---
f1
---
f2
---
```

Anyways, I think I'll leave dealing with multiple application instances as a separate activity, if it gets handled at all.  The shutdown aspects are a thing I think are appropriate for QTrio to make efforts on since QTrio is necessarily tied up in the lifetime of the application.  Creating multiple applications is just a thing you shouldn't do regardless.

**Review by gordon-epc — APPROVED** [review]

**Pull request merged**
